from enum import Enum
import re

raw = '''
# A1a-form (for)
# A1b-plan,dwg (pla)
# A1c-Garden-terrace,balcony,green house,swimming,attic (gar)
# A1d-Privacy-foyer,living,dining,BD,closet,study,Kitchen, powder, (pri)       
# A1e-Public-Entr,TYP lobby (pub)
# A2a-Garden-terrace,balcony,green house,swimming (gar)
# A2b-form (for)
# A2c-plan,dwg (pla)
# A2d-Privacy-foyer,living,dining,BD,closet,study,Kitchen, powder,laundry (pri)
# A2e-Public-Entr,TYP lobby (pub)
# A3a-Garden-terrace,lounge (gar)
# A3b-form (for)
# A3c-plan,dwg (pla)
# A3d-meeting,president room, powder, (mee)
# A3e-studio (stu)
# A3f-Public-Entr,TYP lobby (pub)
# A4a-Garden-terrace,balcony,green house,swimming (gar)
# A4b-form (for)
# A4c-plan,dwg (pla)
# A4d-Privacy-foyer,living,dining,BD,closet,study,Kitchen, powder, (pri)
# A4e-Public-Entr,TYP lobby (pub)
# A5a-institution, laboratory,retire,cemetery (ins)
# A5b-public library (pub)
# A5c-form (for)
# A5d-plan,dwg (pla)
# A5e-kindergarten (kin)
# A5f-university,high school (uni)
# A6a-plan,dwg (pla)
# A6b-exhibition (exh)
# A6c-form (for)
# A7a-form (for)
# A7b-restaurant,Garden-terrace,swimming (res)
# A7c-plan,dwg (pla)
# A7d-room,closet, powder, (roo)
# A7e-Public-Entr,TYP lobby (pub)
# A8a-hall, playground (hal)
# A8b-form (for)
# A8c-plan,dwg (pla)
# A8d-lobby, cafe (lob)
# A9a-form (for)
# A9b-sign (sig)
# A9c-plan,dwg (pla)
# A9d-space (spa)
# A9e-external layer (ext)
# A10a-logo, graphic,image,history (log)
# A10b-club,casino,yacht,cinemas (clu)
# A10c-restaurant (res)
# A10d-Japanese spring,spa,gim,pool (jap)
# A10e-retail (ret)
# A10f-show room,bank,接待中心 (sho)
# A10g-fashion (fas)
# A10h-saloon,beauty shop (sal)
# A10i-(lounge)bar,cafe',cellar ((lo)
# A10j-shopping mall,waterfront,playworld (sho)
# B1a-Furniture and fittings,deco (fur)
# B1b-Landscap,paving,deck,floor,drain (lan)
# B1c-Structure,plastic,tent,slab (str)
# B1d-Lifts,mech,AC,heating,venti (lif)
# B1e-door (doo)
# B1f-Canopy, entrance,shelter (can)
# B1g-Wood (woo)
# B1h- Tile ( ti)
# B1i-counter (cou)
# B1j-column (col)
# B1k-Balconies (bal)
# B1l-Bridge,object,fall,pavilion (bri)
# B1m-Lighting (lig)
# B1n-External walls,fence (ext)
# B1o-Rail (rai)
# B1p-ceiling,courtyard (cei)
# B1q-Staircase,ramp (sta)
# B1r-textile (tex)
# B1s-Masonry,concrete,brick,painting (mas)
# B1t-metal,steel,Texture (met)
# B1u-partition,internal wall,path (par)
# B1v-louver,curtain (lou)
# B1w-Roof,solar,wind,skylight,Green (roo)
# B1x-window (win)
# B1y-Stone (sto)
# B1z-Glass (gla)
'''
    
def main():
  l = ["'" + c[c.find('-')+1:c.rfind(' ')] + "': category3." + c[2:c.find('-')] + "," for c in raw.splitlines()]
  print('\n'.join(l))
    
if __name__ == "__main__":
  main()